version: '3'

networks:
    monitoring_monitor-net: 
        external: true

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.17.1
    hostname: prometheus
    volumes:
      - /var/lib/docker/volumes/portainer_portainer_data/_data/compose/12/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project

  alertmanager:
    hostname: alertmanager
    image: prom/alertmanager:v0.20.0
    volumes:
      - /var/lib/docker/volumes/portainer_portainer_data/_data/compose/12/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    hostname: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project

  grafana:
    image: grafana/grafana:6.7.2
    hostname: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /var/lib/docker/volumes/portainer_portainer_data/_data/compose/12/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project

  pushgateway:
    image: prom/pushgateway:v1.2.0
    hostname: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project

  caddy:
    image: stefanprodan/caddy
    hostname: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - /var/lib/docker/volumes/portainer_portainer_data/_data/compose/12/caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - monitoring_monitor-net
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      placement:
        constraints:
          - node.hostname == SAD-Project
